#!/bin/sh

set -e

cwd=$(pwd)
path="$(pwd)/lib/htmltoword/templates/default.docx"
rm -f $path
cd templates/default

# Zip options:
# r - recursive
# l - convert LF to CR LF line endings
# D - Don't make entries for directories
# T - test the resulting zip
# 9 - Moar compression
# q - quiet
# o - make the file as old as the latest entry
zip -r -l -D -T -9 -q -o $path *

cd $cwd
